service: amigo-frontend
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(gif|png|jpg|css|js|svg|json|woff|woff2|ttf|eot|ico)(|\.map))$
  upload: dist/frontend/(.*)(|\.map)
  static_files: dist/frontend/\1
  secure: always
  redirect_http_response_code: 303

- url: /(.*)
  static_files: dist/frontend/index.html
  upload: dist/frontend/index.html

skip_files:
  - e2e/
  - node_modules/
  - ckeditor5/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE