export interface Test {
    term_id? : number,
    term_exam_id? : number,
    exam_id? : number,
    grade? : string,
    grade_id?: number,
    term_name? : string,
    exam_name? : string,
    chapters? : string,
    topics? : string,
    divisions? : string,
    division_ids? : string,
    subject_id? : number,
    total_marks? : number,
    exam_duration? : number,
    start_date? : string,
    end_date? : string,
    exam_status? : number,
    total_submissions? : number,
    evaluated_submissions? : number,
    score_released? : boolean,
    is_frozen? : boolean,
    test_paper_id? : number,
    exam_type?: string,
    subject_name?: string,
    notes?: string,
    student_exam_status?: number,
    note? : string,
    test_instructions? : string,
    current_status ?:string,
    client_year_id ?: number,
    client_year ?: string
  }